import type { Metadata } from "next";
import Link from "next/link";
import { BUSINESS_EMAIL, BUSINESS_NAME, BUSINESS_PHONE } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `Privacy Policy for ${BUSINESS_NAME}, including Texas Data Privacy and Security Act (TDPSA) consumer rights, cookie and tracking disclosures, and lead-data handling.`,
  alternates: { canonical: "/privacy" },
  robots: { index: true, follow: true },
};

export default function PrivacyPage() {
  return (
    <section className="container-page max-w-3xl py-14">
      <div className="mb-8 rounded-lg border border-highlight/40 bg-highlight/5 px-4 py-3 text-sm font-medium text-highlight-dark">
        Template — owner to review with legal counsel before launch. This is not legal advice.
      </div>

      <h1 className="heading text-4xl text-text">Privacy Policy</h1>
      <p className="mt-2 text-sm text-text-muted">Last updated: TODO — set on launch.</p>

      <div className="prose-legal mt-8 space-y-6 text-text-muted">
        <p>
          This Privacy Policy explains how {BUSINESS_NAME} LLC (&ldquo;we,&rdquo; &ldquo;us,&rdquo;
          or &ldquo;our&rdquo;) collects, uses, and shares information when you visit our website or
          request a quote. We are committed to protecting your privacy and being transparent about
          our data practices.
        </p>

        <h2 className="heading text-2xl text-text">Information We Collect</h2>
        <p>When you submit a quote or contact request, we collect the information you provide:</p>
        <ul className="list-disc space-y-1 pl-6">
          <li>Name and contact details (phone, and email if provided)</li>
          <li>Service details (service type, property type, city, square footage, message)</li>
          <li>Any estimate generated by our commercial calculator</li>
          <li>
            Marketing attribution data (UTM parameters) and standard analytics data such as pages
            viewed, device/browser type, and approximate location
          </li>
        </ul>

        <h2 className="heading text-2xl text-text">How We Use Your Information</h2>
        <ul className="list-disc space-y-1 pl-6">
          <li>To respond to your request and provide quotes and services</li>
          <li>To contact you about your project</li>
          <li>To measure and improve our marketing and website performance</li>
          <li>To comply with legal obligations</li>
        </ul>

        <h2 className="heading text-2xl text-text">Cookies, Analytics & Advertising (Consent)</h2>
        <p>
          We use cookies and similar technologies for analytics and advertising. Specifically, we
          may use Google Tag Manager, Google Analytics 4 (GA4), and the Meta (Facebook) Pixel to
          understand site usage and measure the effectiveness of our marketing.
        </p>
        <p>
          We implement <strong>Google Consent Mode v2</strong>. By default, storage for analytics
          and advertising (<code>analytics_storage</code>, <code>ad_storage</code>,{" "}
          <code>ad_user_data</code>, <code>ad_personalization</code>) is set to{" "}
          <strong>denied</strong> until you make a choice in our cookie banner. If you accept,
          these tags are enabled; if you decline, non-essential tracking remains disabled. You can
          change your choice by clearing the <code>dbpw_consent</code> cookie in your browser.
        </p>

        <h2 className="heading text-2xl text-text">How We Share Information</h2>
        <p>
          We do not sell your personal information. We share lead data only as needed to deliver our
          services (for example, with the service providers that host our website, store our leads,
          and send our notification emails) and as required by law. We do not share your information
          with unrelated third parties for their own marketing.
        </p>

        <h2 className="heading text-2xl text-text">Data Retention</h2>
        <p>
          We retain lead and contact information for as long as necessary to provide services,
          maintain business records, and comply with legal obligations, after which it is deleted or
          anonymized. TODO: confirm a specific retention period with counsel.
        </p>

        <h2 className="heading text-2xl text-text">Your Texas Privacy Rights (TDPSA)</h2>
        <p>
          Under the <strong>Texas Data Privacy and Security Act (TDPSA)</strong>, Texas residents
          have the right to:
        </p>
        <ul className="list-disc space-y-1 pl-6">
          <li>Confirm whether we are processing your personal data and access that data</li>
          <li>Correct inaccuracies in your personal data</li>
          <li>Delete personal data we have collected from you</li>
          <li>
            Obtain a portable copy of personal data you previously provided, where applicable
          </li>
          <li>
            Opt out of the processing of your personal data for purposes of targeted advertising,
            the sale of personal data, or certain profiling
          </li>
        </ul>
        <p>
          To exercise any of these rights, contact us at{" "}
          <a href={`mailto:${BUSINESS_EMAIL}`} className="text-primary underline">
            {BUSINESS_EMAIL}
          </a>{" "}
          or {BUSINESS_PHONE}. We will respond as required by law. You also have the right to appeal
          a decision regarding your request; if we deny your request, we will provide instructions
          for how to appeal.
        </p>

        <h2 className="heading text-2xl text-text">Children&rsquo;s Privacy</h2>
        <p>
          Our website and services are intended for adults. We do not knowingly collect personal
          information from children.
        </p>

        <h2 className="heading text-2xl text-text">Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. The &ldquo;last updated&rdquo; date
          above reflects the most recent revision.
        </p>

        <h2 className="heading text-2xl text-text">Contact Us</h2>
        <p>
          Questions about this policy or your data? Contact {BUSINESS_NAME} at{" "}
          <a href={`mailto:${BUSINESS_EMAIL}`} className="text-primary underline">
            {BUSINESS_EMAIL}
          </a>{" "}
          or {BUSINESS_PHONE}. See also our{" "}
          <Link href="/terms" className="text-primary underline">
            Terms of Service
          </Link>
          .
        </p>
      </div>
    </section>
  );
}
